package com.zywczas.storevideo.usecase

import com.zywczas.storevideo.dao.VideoDatabaseDao
import com.zywczas.storevideo.entity.VideoLocal

class SaveVideoUseCase internal constructor(private val videoDatabaseDao: VideoDatabaseDao) {

    suspend fun save(video: VideoLocal) {
        videoDatabaseDao.dbQuery.insertVideoWithAutoGeneratedId(
            timeStamp = video.timeStamp,
            description = video.description,
            uri = video.uri
        )
    }
}
